In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### **1. Load the CSV with pandas and display the first 10 records, shape, column names and data types.**

In [2]:
df = pd.read_csv('india-districts-census-2011.csv')

In [3]:
df

,District code,State name,District name,Population,Male,Female,Literate,Male_Literate,Female_Literate,SC,...,Power_Parity_Rs_90000_150000,Power_Parity_Rs_45000_150000,Power_Parity_Rs_150000_240000,Power_Parity_Rs_240000_330000,Power_Parity_Rs_150000_330000,Power_Parity_Rs_330000_425000,Power_Parity_Rs_425000_545000,Power_Parity_Rs_330000_545000,Power_Parity_Above_Rs_545000,Total_Power_Parity
0,1,JAMMU AND KASHMIR,Kupwara,870354,474190,396164,439654,282823,156831,1048,...,94,588,71,101,172,74,10,84,15,1119
1,2,JAMMU AND KASHMIR,Badgam,753745,398041,355704,335649,207741,127908,368,...,126,562,72,89,161,96,28,124,18,1066
2,3,JAMMU AND KASHMIR,Leh(Ladakh),133487,78971,54516,93770,62834,30936,488,...,46,122,15,22,37,20,14,34,17,242
3,4,JAMMU AND KASHMIR,Kargil,140802,77785,63017,86236,56301,29935,18,...,27,114,12,18,30,19,3,22,7,214
4,5,JAMMU AND KASHMIR,Punch,476835,251899,224936,261724,163333,98391,556,...,78,346,35,50,85,59,8,67,12,629
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
635,636,PONDICHERRY,Mahe,41816,19143,22673,36470,16610,19860,144,...,2316,4309,1370,838,2208,576,978,1554,1446,10027
636,637,PONDICHERRY,Karaikal,200222,97809,102413,154916,79903,75013,35348,...,1063,2408,665,340,1005,246,483,729,341,4890
637,638,ANDAMAN AND NICOBAR ISLANDS,Nicobars,36842,20727,16115,25332,15397,9935,0,...,685,1895,212,134,346,70,120,190,84,3151
638,639,ANDAMAN AND NICOBAR ISLANDS,North AND Middle Andaman,105597,54861,50736,78683,43186,35497,0,...,685,1895,212,134,346,70,120,190,84,3151
639,640,ANDAMAN AND NICOBAR ISLANDS,South Andaman,238142,127283,110859,190266,105794,84472,0,...,1371,3020,649,368,1017,265,497,762,376,5782

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 640 entries, 0 to 639
Columns: 118 entries, District code to Total_Power_Parity
dtypes: int64(116), str(2)
memory usage: 590.1 KB

In [5]:
df.dtypes

District code                    int64
State name                         str
District name                      str
Population                       int64
Male                             int64
                                 ...
Power_Parity_Rs_330000_425000    int64
Power_Parity_Rs_425000_545000    int64
Power_Parity_Rs_330000_545000    int64
Power_Parity_Above_Rs_545000     int64
Total_Power_Parity               int64
Length: 118, dtype: object

In [6]:
df.describe()

,District code,Population,Male,Female,Literate,Male_Literate,Female_Literate,SC,Male_SC,Female_SC,...,Power_Parity_Rs_90000_150000,Power_Parity_Rs_45000_150000,Power_Parity_Rs_150000_240000,Power_Parity_Rs_240000_330000,Power_Parity_Rs_150000_330000,Power_Parity_Rs_330000_425000,Power_Parity_Rs_425000_545000,Power_Parity_Rs_330000_545000,Power_Parity_Above_Rs_545000,Total_Power_Parity
count,640.000000,6.400000e+02,6.400000e+02,6.400000e+02,6.400000e+02,6.400000e+02,6.400000e+02,6.400000e+02,6.400000e+02,6.400000e+02,...,640.000000,640.000000,640.000000,640.000000,640.000000,640.000000,640.000000,640.000000,640.000000,640.000000
mean,320.500000,1.891961e+06,9.738598e+05,9.181011e+05,1.193186e+06,6.793182e+05,5.138675e+05,3.146537e+05,1.617739e+05,1.528798e+05,...,786.046875,1696.456250,294.000000,215.300000,509.300000,194.204688,261.245313,455.450000,279.631250,3315.412500
std,184.896367,1.544380e+06,8.007785e+05,7.449864e+05,1.068583e+06,5.924144e+05,4.801816e+05,3.129818e+05,1.611216e+05,1.520336e+05,...,1038.854733,1720.535151,638.345281,362.684243,968.538748,424.108001,587.279450,1007.364839,1050.934537,4638.568719
min,1.000000,8.004000e+03,4.414000e+03,3.590000e+03,4.436000e+03,2.614000e+03,1.822000e+03,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.000000
25%,160.750000,8.178610e+05,4.171682e+05,4.017458e+05,4.825982e+05,2.764365e+05,2.008920e+05,8.320850e+04,4.230700e+04,4.267175e+04,...,236.750000,589.000000,59.000000,24.750000,95.000000,19.000000,21.000000,44.000000,18.000000,1024.250000
50%,320.500000,1.557367e+06,7.986815e+05,7.589200e+05,9.573465e+05,5.483525e+05,4.038590e+05,2.460160e+05,1.255485e+05,1.178550e+05,...,518.000000,1220.500000,149.000000,118.500000,278.000000,84.000000,85.500000,186.500000,60.500000,2238.500000
75%,480.250000,2.583551e+06,1.338604e+06,1.264277e+06,1.602260e+06,9.188582e+05,6.641550e+05,4.477078e+05,2.284602e+05,2.140502e+05,...,941.250000,2233.250000,296.500000,262.000000,564.500000,213.250000,293.000000,497.000000,215.500000,3959.000000
max,640.000000,1.106015e+07,5.865078e+06,5.195070e+06,8.227161e+06,4.591396e+06,3.635765e+06,2.464032e+06,1.266504e+06,1.197528e+06,...,10334.000000,13819.000000,10835.000000,3595.000000,14430.000000,5027.000000,7597.000000,12624.000000,18289.000000,60163.000000

In [7]:
df.columns = df.columns.str.lower().str.replace(' ','_')

In [8]:
df.state_name = df.state_name.str.title()

In [9]:
df.district_name = df.district_name.str.title()

In [10]:
df['sex_ratio'] = ((df.female / df.male) * 100).round(2)

C:\Users\Tonmoy Dey\AppData\Local\Temp\ipykernel_38616\3402824340.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['sex_ratio'] = ((df.female / df.male) * 100).round(2)

In [11]:
df

,district_code,state_name,district_name,population,male,female,literate,male_literate,female_literate,sc,...,power_parity_rs_45000_150000,power_parity_rs_150000_240000,power_parity_rs_240000_330000,power_parity_rs_150000_330000,power_parity_rs_330000_425000,power_parity_rs_425000_545000,power_parity_rs_330000_545000,power_parity_above_rs_545000,total_power_parity,sex_ratio
0,1,Jammu And Kashmir,Kupwara,870354,474190,396164,439654,282823,156831,1048,...,588,71,101,172,74,10,84,15,1119,83.55
1,2,Jammu And Kashmir,Badgam,753745,398041,355704,335649,207741,127908,368,...,562,72,89,161,96,28,124,18,1066,89.36
2,3,Jammu And Kashmir,Leh(Ladakh),133487,78971,54516,93770,62834,30936,488,...,122,15,22,37,20,14,34,17,242,69.03
3,4,Jammu And Kashmir,Kargil,140802,77785,63017,86236,56301,29935,18,...,114,12,18,30,19,3,22,7,214,81.01
4,5,Jammu And Kashmir,Punch,476835,251899,224936,261724,163333,98391,556,...,346,35,50,85,59,8,67,12,629,89.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
635,636,Pondicherry,Mahe,41816,19143,22673,36470,16610,19860,144,...,4309,1370,838,2208,576,978,1554,1446,10027,118.44
636,637,Pondicherry,Karaikal,200222,97809,102413,154916,79903,75013,35348,...,2408,665,340,1005,246,483,729,341,4890,104.71
637,638,Andaman And Nicobar Islands,Nicobars,36842,20727,16115,25332,15397,9935,0,...,1895,212,134,346,70,120,190,84,3151,77.75
638,639,Andaman And Nicobar Islands,North And Middle Andaman,105597,54861,50736,78683,43186,35497,0,...,1895,212,134,346,70,120,190,84,3151,92.48
639,640,Andaman And Nicobar Islands,South Andaman,238142,127283,110859,190266,105794,84472,0,...,3020,649,368,1017,265,497,762,376,5782,87.10

# **Python Data Cleaning**

### **2. Identify missing values in every column and display the 10 columns with the highest missing-value counts.**

In [12]:
df.isnull().sum()

district_code                    0
state_name                       0
district_name                    0
population                       0
male                             0
                                ..
power_parity_rs_425000_545000    0
power_parity_rs_330000_545000    0
power_parity_above_rs_545000     0
total_power_parity               0
sex_ratio                        0
Length: 119, dtype: int64

#### **There are no missing values in this dataset**

### **3. Check whether District code contains duplicates and report the number of duplicate district records.**

In [13]:
df.district_code.duplicated().sum()

np.int64(0)

#### **There are no duplicate values**

### **4. Check all population, literacy, worker and household count fields for negative or nonnumeric values.**

In [14]:
df[(df.population < 0) | (df.literate < 0) | (df.workers < 0) | (df.households < 0)]

Empty DataFrame
Columns: [district_code, state_name, district_name, population, male, female, literate, male_literate, female_literate, sc, male_sc, female_sc, st, male_st, female_st, workers, male_workers, female_workers, main_workers, marginal_workers, non_workers, cultivator_workers, agricultural_workers, household_workers, other_workers, hindus, muslims, christians, sikhs, buddhists, jains, others_religions, religion_not_stated, lpg_or_png_households, housholds_with_electric_lighting, households_with_internet, households_with_computer, rural_households, urban_households, households, below_primary_education, primary_education, middle_education, secondary_education, higher_education, graduate_education, other_education, literate_education, illiterate_education, total_education, age_group_0_29, age_group_30_49, age_group_50, age_not_stated, households_with_bicycle, households_with_car_jeep_van, households_with_radio_transistor, households_with_scooter_motorcycle_moped, households_with_telephone_mobile_phone_landline_only, households_with_telephone_mobile_phone_mobile_only, households_with_tv_computer_laptop_telephone_mobile_phone_and_scooter_car, households_with_television, households_with_telephone_mobile_phone, households_with_telephone_mobile_phone_both, condition_of_occupied_census_houses_dilapidated_households, households_with_separate_kitchen_cooking_inside_house, having_bathing_facility_total_households, having_latrine_facility_within_the_premises_total_households, ownership_owned_households, ownership_rented_households, type_of_bathing_facility_enclosure_without_roof_households, type_of_fuel_used_for_cooking_any_other_households, type_of_latrine_facility_pit_latrine_households, type_of_latrine_facility_other_latrine_households, type_of_latrine_facility_night_soil_disposed_into_open_drain_households, type_of_latrine_facility_flush_pour_flush_latrine_connected_to_other_system_households, not_having_bathing_facility_within_the_premises_total_households, not_having_latrine_facility_within_the_premises_alternative_source_open_households, main_source_of_drinking_water_un_covered_well_households, main_source_of_drinking_water_handpump_tubewell_borewell_households, main_source_of_drinking_water_spring_households, main_source_of_drinking_water_river_canal_households, main_source_of_drinking_water_other_sources_households, main_source_of_drinking_water_other_sources_spring_river_canal_tank_pond_lake_other_sources__households, location_of_drinking_water_source_near_the_premises_households, location_of_drinking_water_source_within_the_premises_households, main_source_of_drinking_water_tank_pond_lake_households, main_source_of_drinking_water_tapwater_households, main_source_of_drinking_water_tubewell_borehole_households, household_size_1_person_households, household_size_2_persons_households, household_size_1_to_2_persons, household_size_3_persons_households, household_size_3_to_5_persons_households, household_size_4_persons_households, household_size_5_persons_households, household_size_6_8_persons_households, household_size_9_persons_and_above_households, location_of_drinking_water_source_away_households, married_couples_1_households, ...]
Index: []

[0 rows x 119 columns]

#### **There are no negetive values**

In [15]:
#literacy percentage column
df['literacy_percentage'] = ((df.literate/df.population)/100).round(2)

C:\Users\Tonmoy Dey\AppData\Local\Temp\ipykernel_38616\2001436242.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['literacy_percentage'] = ((df.literate/df.population)/100).round(2)

In [16]:
df.drop(columns='literacy percentage',inplace=True)

KeyError: "['literacy percentage'] not found in axis"

In [ ]:
df

,district_code,state_name,district_name,population,male,female,literate,male_literate,female_literate,sc,...,power_parity_rs_150000_240000,power_parity_rs_240000_330000,power_parity_rs_150000_330000,power_parity_rs_330000_425000,power_parity_rs_425000_545000,power_parity_rs_330000_545000,power_parity_above_rs_545000,total_power_parity,sex_ratio,literacy_percentage
0,1,Jammu And Kashmir,Kupwara,870354,474190,396164,439654,282823,156831,1048,...,71,101,172,74,10,84,15,1119,83.55,0.01
1,2,Jammu And Kashmir,Badgam,753745,398041,355704,335649,207741,127908,368,...,72,89,161,96,28,124,18,1066,89.36,0.00
2,3,Jammu And Kashmir,Leh(Ladakh),133487,78971,54516,93770,62834,30936,488,...,15,22,37,20,14,34,17,242,69.03,0.01
3,4,Jammu And Kashmir,Kargil,140802,77785,63017,86236,56301,29935,18,...,12,18,30,19,3,22,7,214,81.01,0.01
4,5,Jammu And Kashmir,Punch,476835,251899,224936,261724,163333,98391,556,...,35,50,85,59,8,67,12,629,89.30,0.01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
635,636,Pondicherry,Mahe,41816,19143,22673,36470,16610,19860,144,...,1370,838,2208,576,978,1554,1446,10027,118.44,0.01
636,637,Pondicherry,Karaikal,200222,97809,102413,154916,79903,75013,35348,...,665,340,1005,246,483,729,341,4890,104.71,0.01
637,638,Andaman And Nicobar Islands,Nicobars,36842,20727,16115,25332,15397,9935,0,...,212,134,346,70,120,190,84,3151,77.75,0.01
638,639,Andaman And Nicobar Islands,North And Middle Andaman,105597,54861,50736,78683,43186,35497,0,...,212,134,346,70,120,190,84,3151,92.48,0.01
639,640,Andaman And Nicobar Islands,South Andaman,238142,127283,110859,190266,105794,84472,0,...,649,368,1017,265,497,762,376,5782,87.10,0.01

# **Data Analysis**

## **1. Which 10 states have the highest total population? Aggregate district records by state.**

In [ ]:
df.groupby(['state_name']).population.sum().sort_values(ascending=False).head(10)

state_name
Uttar Pradesh     199812341
Maharashtra       112374333
Bihar             104099452
West Bengal        91276115
Andhra Pradesh     84580777
Madhya Pradesh     72626809
Tamil Nadu         72147030
Rajasthan          68548437
Karnataka          61095297
Gujarat            60439692
Name: population, dtype: int64

#### **Uttar Pradesh, Maharashtra, Bihar, Andhra Pradesh, etc are the top 10 states with highest population.**

## **2. Which 10 districts have the highest population? Include their state names.**

In [ ]:
df.groupby(['district_name','state_name'],as_index=False).population.sum().sort_values(by = 'population',ascending=False).head(10)

                  district_name   state_name  population
574                       Thane  Maharashtra    11060148
425  North Twenty Four Parganas  West Bengal    10009781
46                    Bangalore    Karnataka     9621551
460                        Pune  Maharashtra     9429408
389             Mumbai Suburban  Maharashtra     9356962
557  South Twenty Four Parganas  West Bengal     8161961
54                   Barddhaman  West Bengal     7717563
2                     Ahmadabad      Gujarat     7214225
391                 Murshidabad  West Bengal     7103807
238                      Jaipur    Rajasthan     6626178

## **3. Which five states have the highest and lowest female-to-male ratios?**

In [ ]:
df.groupby(['state_name']).sex_ratio.mean().round(2).sort_values(ascending=False).head(10)

state_name
Kerala            108.04
Pondicherry       107.46
Uttarakhand       101.05
Tamil Nadu         99.94
Chhattisgarh       99.48
Andhra Pradesh     99.47
Karnataka          98.43
Orissa             98.39
Meghalaya          97.97
Manipur            97.56
Name: sex_ratio, dtype: float64

## **4.  What is the overall literacy percentage (Literate / Population × 100) for each state? Rank states by percentage**

In [ ]:
df.groupby('state_name').literacy_percentage.sum()

state_name
Andaman And Nicobar Islands    0.03
Andhra Pradesh                 0.22
Arunachal Pradesh              0.11
Assam                          0.26
Bihar                          0.21
Chandigarh                     0.01
Chhattisgarh                   0.14
Dadra And Nagar Haveli         0.01
Daman And Diu                  0.02
Goa                            0.02
Gujarat                        0.25
Haryana                        0.20
Himachal Pradesh               0.12
Jammu And Kashmir              0.15
Jharkhand                      0.17
Karnataka                      0.29
Kerala                         0.14
Lakshadweep                    0.01
Madhya Pradesh                 0.44
Maharashtra                    0.35
Manipur                        0.09
Meghalaya                      0.06
Mizoram                        0.08
Nagaland                       0.10
Nct Of Delhi                   0.09
Orissa                         0.24
Pondicherry                    0.04
Punjab                         0.20
Rajasthan                      0.26
Sikkim                         0.04
Tamil Nadu                     0.32
Tripura                        0.04
Uttar Pradesh                  0.61
Uttarakhand                    0.13
West Bengal                    0.18
Name: literacy_percentage, dtype: float64

## **5. Which 10 districts have the lowest female literacy percentage (Female_Literate / Female × 100), excluding zero denominators?**

In [ ]:
df

,district_code,state_name,district_name,population,male,female,literate,male_literate,female_literate,sc,...,power_parity_rs_150000_240000,power_parity_rs_240000_330000,power_parity_rs_150000_330000,power_parity_rs_330000_425000,power_parity_rs_425000_545000,power_parity_rs_330000_545000,power_parity_above_rs_545000,total_power_parity,sex_ratio,literacy_percentage
0,1,Jammu And Kashmir,Kupwara,870354,474190,396164,439654,282823,156831,1048,...,71,101,172,74,10,84,15,1119,83.55,0.01
1,2,Jammu And Kashmir,Badgam,753745,398041,355704,335649,207741,127908,368,...,72,89,161,96,28,124,18,1066,89.36,0.00
2,3,Jammu And Kashmir,Leh(Ladakh),133487,78971,54516,93770,62834,30936,488,...,15,22,37,20,14,34,17,242,69.03,0.01
3,4,Jammu And Kashmir,Kargil,140802,77785,63017,86236,56301,29935,18,...,12,18,30,19,3,22,7,214,81.01,0.01
4,5,Jammu And Kashmir,Punch,476835,251899,224936,261724,163333,98391,556,...,35,50,85,59,8,67,12,629,89.30,0.01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
635,636,Pondicherry,Mahe,41816,19143,22673,36470,16610,19860,144,...,1370,838,2208,576,978,1554,1446,10027,118.44,0.01
636,637,Pondicherry,Karaikal,200222,97809,102413,154916,79903,75013,35348,...,665,340,1005,246,483,729,341,4890,104.71,0.01
637,638,Andaman And Nicobar Islands,Nicobars,36842,20727,16115,25332,15397,9935,0,...,212,134,346,70,120,190,84,3151,77.75,0.01
638,639,Andaman And Nicobar Islands,North And Middle Andaman,105597,54861,50736,78683,43186,35497,0,...,212,134,346,70,120,190,84,3151,92.48,0.01
639,640,Andaman And Nicobar Islands,South Andaman,238142,127283,110859,190266,105794,84472,0,...,649,368,1017,265,497,762,376,5782,87.10,0.01

In [ ]:
df['female_literacy_percentage'] = ((df.female_literate/df.female)/100).round(2)

In [ ]:
df.female_literacy_percentage

0      0.00
1      0.00
2      0.01
3      0.00
4      0.00
       ...
635    0.01
636    0.01
637    0.01
638    0.01
639    0.01
Name: female_literacy_percentage, Length: 640, dtype: float64

In [ ]:
df.groupby('district_name').female_literacy_percentage.mean().sort_values().head(10)

district_name
Adilabad           0.0
Yadgir             0.0
Alwar              0.0
Alirajpur          0.0
Aligarh            0.0
Ajmer              0.0
Banka              0.0
Uttar Dinajpur     0.0
Upper Subansiri    0.0
Upper Siang        0.0
Name: female_literacy_percentage, dtype: float64

## **6.  For each state, what are the total Workers and Non_Workers, and what percentage of the population are Workers?**

In [ ]:
df.head(2)

,district_code,state_name,district_name,population,male,female,literate,male_literate,female_literate,sc,...,power_parity_rs_240000_330000,power_parity_rs_150000_330000,power_parity_rs_330000_425000,power_parity_rs_425000_545000,power_parity_rs_330000_545000,power_parity_above_rs_545000,total_power_parity,sex_ratio,literacy_percentage,female_literacy_percentage
0,1,Jammu And Kashmir,Kupwara,870354,474190,396164,439654,282823,156831,1048,...,101,172,74,10,84,15,1119,83.55,0.01,0.0
1,2,Jammu And Kashmir,Badgam,753745,398041,355704,335649,207741,127908,368,...,89,161,96,28,124,18,1066,89.36,0.00,0.0

In [ ]:
df['worker_percentage'] = ((df.workers/df.population) * 100).round(2)

In [ ]:
df.groupby('state_name')[['workers','non_workers','worker_percentage']].sum()

                              workers  non_workers  worker_percentage
state_name
Andaman And Nicobar Islands    152535       228046             123.67
Andhra Pradesh               39422906     45157871            1079.96
Arunachal Pradesh              587657       796070             701.70
Assam                        11969690     19235886            1047.07
Bihar                        34724987     69374465            1274.11
Chandigarh                     404136       651314              38.29
Chhattisgarh                 12180225     13364973             888.20
Dadra And Nagar Haveli         157161       186548              45.73
Daman And Diu                  121271       121976              85.45
Goa                            577248       881297              79.03
Gujarat                      24767747     35671945            1103.12
Haryana                       8916508     16434954             737.13
Himachal Pradesh              3559422      3305180             653.82
Jammu And Kashmir             4322713      8218589             790.97
Jharkhand                    13098274     19889860             984.78
Karnataka                    27872597     33222700            1387.31
Kerala                       11619063     21786998             502.86
Lakshadweep                     18753        45720              29.09
Madhya Pradesh               31574133     41052676            2202.92
Maharashtra                  49427878     62946455            1582.40
Manipur                       1304610      1551184             420.92
Meghalaya                     1185619      1781270             279.01
Mizoram                        486705       610501             352.29
Nagaland                       974122      1004380             564.08
Nct Of Delhi                  5587049     11200892             309.74
Orissa                       17541589     24432629            1298.22
Pondicherry                    444968       802985             129.09
Punjab                        9897362     17845976             714.31
Rajasthan                    29886255     38662182            1470.38
Sikkim                         308138       302439             205.15
Tamil Nadu                   32884681     39262349            1480.81
Tripura                       1469521      2204396             159.37
Uttar Pradesh                65814715    133997626            2373.68
Uttarakhand                   3872275      6214017             544.51
West Bengal                  34756355     56519760             732.01

## **7.  Which 10 districts have the highest share of agricultural workers (Agricultural_Workers / Workers × 100)?**

In [ ]:
df.head(2)

,district_code,state_name,district_name,population,male,female,literate,male_literate,female_literate,sc,...,power_parity_rs_150000_330000,power_parity_rs_330000_425000,power_parity_rs_425000_545000,power_parity_rs_330000_545000,power_parity_above_rs_545000,total_power_parity,sex_ratio,literacy_percentage,female_literacy_percentage,worker_percentage
0,1,Jammu And Kashmir,Kupwara,870354,474190,396164,439654,282823,156831,1048,...,172,74,10,84,15,1119,83.55,0.01,0.0,26.32
1,2,Jammu And Kashmir,Badgam,753745,398041,355704,335649,207741,127908,368,...,161,96,28,124,18,1066,89.36,0.00,0.0,28.51

In [ ]:
df['agriculture_workers_share'] = ((df.agricultural_workers/df.workers)/100).round(2)

C:\Users\Tonmoy Dey\AppData\Local\Temp\ipykernel_12996\1782996553.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['agriculture_workers_share'] = ((df.agricultural_workers/df.workers)/100).round(2)

In [ ]:
df.groupby('district_name')['agriculture_workers_share'].sum().sort_values(ascending=False).head(10)

district_name
Araria                  0.01
Kaushambi               0.01
Arwal                   0.01
Banka                   0.01
Guntur                  0.01
Aurangabad              0.01
Khandwa (East Nimar)    0.01
Darbhanga               0.01
Akola                   0.01
Gajapati                0.01
Name: agriculture_workers_share, dtype: float64

## **8.  Which states have the highest number of Households_with_Internet, and what is the percentage relative to Households?**

In [ ]:
df.head(5)

,district_code,state_name,district_name,population,male,female,literate,male_literate,female_literate,sc,...,power_parity_rs_150000_240000,power_parity_rs_240000_330000,power_parity_rs_150000_330000,power_parity_rs_330000_425000,power_parity_rs_425000_545000,power_parity_rs_330000_545000,power_parity_above_rs_545000,total_power_parity,sex_ratio,literacy_percentage
0,1,Jammu And Kashmir,Kupwara,870354,474190,396164,439654,282823,156831,1048,...,71,101,172,74,10,84,15,1119,83.55,0.01
1,2,Jammu And Kashmir,Badgam,753745,398041,355704,335649,207741,127908,368,...,72,89,161,96,28,124,18,1066,89.36,0.00
2,3,Jammu And Kashmir,Leh(Ladakh),133487,78971,54516,93770,62834,30936,488,...,15,22,37,20,14,34,17,242,69.03,0.01
3,4,Jammu And Kashmir,Kargil,140802,77785,63017,86236,56301,29935,18,...,12,18,30,19,3,22,7,214,81.01,0.01
4,5,Jammu And Kashmir,Punch,476835,251899,224936,261724,163333,98391,556,...,35,50,85,59,8,67,12,629,89.30,0.01

In [ ]:
df.groupby('state_name').households_with_internet.sum().sort_values(ascending=False).head(5)

state_name
Maharashtra      1379351
Tamil Nadu        772257
Karnataka         638468
Uttar Pradesh     609773
Nct Of Delhi      588951
Name: households_with_internet, dtype: int64

In [ ]:
df['households_percentage'] = ((df.households_with_internet / df.households) * 100).round(2)

C:\Users\Tonmoy Dey\AppData\Local\Temp\ipykernel_33916\93387718.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['households_percentage'] = ((df.households_with_internet / df.households) * 100).round(2)

In [ ]:
df.groupby('state_name')[['households_with_internet','households_percentage']].sum().sort_values( by = 'households_with_internet',ascending=False).head(5)

               households_with_internet  households_percentage
state_name
Maharashtra                     1379351                  79.23
Tamil Nadu                       772257                  81.10
Karnataka                        638468                  51.18
Uttar Pradesh                    609773                  81.94
Nct Of Delhi                     588951                 111.40

## **9. Which states have the highest share of households with internet access? Rank the top 10.**

In [ ]:
df.head(5)

,district_code,state_name,district_name,population,male,female,literate,male_literate,female_literate,sc,...,power_parity_rs_240000_330000,power_parity_rs_150000_330000,power_parity_rs_330000_425000,power_parity_rs_425000_545000,power_parity_rs_330000_545000,power_parity_above_rs_545000,total_power_parity,sex_ratio,literacy_percentage,households_percentage
0,1,Jammu And Kashmir,Kupwara,870354,474190,396164,439654,282823,156831,1048,...,101,172,74,10,84,15,1119,83.55,0.01,0.42
1,2,Jammu And Kashmir,Badgam,753745,398041,355704,335649,207741,127908,368,...,89,161,96,28,124,18,1066,89.36,0.00,1.06
2,3,Jammu And Kashmir,Leh(Ladakh),133487,78971,54516,93770,62834,30936,488,...,22,37,20,14,34,17,242,69.03,0.01,1.06
3,4,Jammu And Kashmir,Kargil,140802,77785,63017,86236,56301,29935,18,...,18,30,19,3,22,7,214,81.01,0.01,0.49
4,5,Jammu And Kashmir,Punch,476835,251899,224936,261724,163333,98391,556,...,50,85,59,8,67,12,629,89.30,0.01,0.23

In [ ]:
df['households_share_with_internet'] = ((df.households_with_internet/df.households)*100).round(2)

In [ ]:
df

,district_code,state_name,district_name,population,male,female,literate,male_literate,female_literate,sc,...,power_parity_rs_150000_330000,power_parity_rs_330000_425000,power_parity_rs_425000_545000,power_parity_rs_330000_545000,power_parity_above_rs_545000,total_power_parity,sex_ratio,literacy_percentage,households_percentage,households_share_with_internet
0,1,Jammu And Kashmir,Kupwara,870354,474190,396164,439654,282823,156831,1048,...,172,74,10,84,15,1119,83.55,0.01,0.42,0.42
1,2,Jammu And Kashmir,Badgam,753745,398041,355704,335649,207741,127908,368,...,161,96,28,124,18,1066,89.36,0.00,1.06,1.06
2,3,Jammu And Kashmir,Leh(Ladakh),133487,78971,54516,93770,62834,30936,488,...,37,20,14,34,17,242,69.03,0.01,1.06,1.06
3,4,Jammu And Kashmir,Kargil,140802,77785,63017,86236,56301,29935,18,...,30,19,3,22,7,214,81.01,0.01,0.49,0.49
4,5,Jammu And Kashmir,Punch,476835,251899,224936,261724,163333,98391,556,...,85,59,8,67,12,629,89.30,0.01,0.23,0.23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
635,636,Pondicherry,Mahe,41816,19143,22673,36470,16610,19860,144,...,2208,576,978,1554,1446,10027,118.44,0.01,4.74,4.74
636,637,Pondicherry,Karaikal,200222,97809,102413,154916,79903,75013,35348,...,1005,246,483,729,341,4890,104.71,0.01,2.69,2.69
637,638,Andaman And Nicobar Islands,Nicobars,36842,20727,16115,25332,15397,9935,0,...,346,70,120,190,84,3151,77.75,0.01,0.36,0.36
638,639,Andaman And Nicobar Islands,North And Middle Andaman,105597,54861,50736,78683,43186,35497,0,...,346,70,120,190,84,3151,92.48,0.01,0.97,0.97
639,640,Andaman And Nicobar Islands,South Andaman,238142,127283,110859,190266,105794,84472,0,...,1017,265,497,762,376,5782,87.10,0.01,3.26,3.26

In [ ]:
df.groupby('state_name').households_share_with_internet.sum().round(2).sort_values(ascending=False).head(10)

state_name
Nct Of Delhi      111.40
Uttar Pradesh      81.94
Tamil Nadu         81.10
Maharashtra        79.23
Haryana            68.69
Punjab             66.55
Kerala             55.53
Karnataka          51.18
Andhra Pradesh     45.00
Madhya Pradesh     42.84
Name: households_share_with_internet, dtype: float64

# **KPI Requirements**

## **1. Calculate the total population across all districts.**

In [ ]:
print(f'The total population accross all districts are : {df.population.sum()}.')

The total population accross all districts are : 1210854977.

## **2. Calculate the total male population and total female population.**

In [ ]:
print(f'The total male population is : {df.male.sum()} and female population is : {df.female.sum()}')

The total male population is : 623270258 and female population is : 587584719

## **3. Calculate the number of unique states and the number of unique districts.**

In [20]:
print(f'The number of unique states are : {df.state_name.nunique()} and the districts are : {df.district_name.nunique()}')

The number of unique states are : 35 and the districts are : 634

## **4. Calculate the total number of households.**

In [21]:
print(f'The total no of households are {df.households.sum()}')

The total no of households are 330835767

## **5. Calculate the overall literacy percentage: total Literate / total Population × 100.**

In [23]:
print(f'The overall literacy percentage is {((df.literate.sum()/df.population.sum())*100).round(2)}')

The overall literacy percentage is 63.07

## **6. Calculate the male and female literacy percentages separately.**

In [ ]:
print()